import { z } from 'zod';

export const RestBranchSchema = z.looseObject({
  id: z.string().optional(),
  displayId: z.string().optional(),
  type: z.string().optional(),
  latestCommit: z.string().optional(),
  latestChangeset: z.string().optional(),
  isDefault: z.boolean().optional(),
  metadata: z.looseObject({
    'com.atlassian.bitbucket.server.bitbucket-jira:branch-list-jira-issues': z.array(z.unknown()).optional(),
    'com.atlassian.bitbucket.server.bitbucket-branch:ahead-behind-metadata-provider': z.looseObject({
      ahead: z.number().optional(),
      behind: z.number().optional(),
    }).optional(),
    'com.atlassian.bitbucket.server.bitbucket-branch:latest-commit-metadata': z.looseObject({
      id: z.string().optional(),
      displayId: z.string().optional(),
      author: z.looseObject({
        name: z.string().optional(),
        emailAddress: z.string().optional(),
        active: z.boolean().optional(),
        displayName: z.string().optional(),
        id: z.number().optional(),
        slug: z.string().optional(),
        type: z.string().optional(),
        links: z.looseObject({
          self: z.array(z.looseObject({
            href: z.string().optional(),
          })).optional(),
        }).optional(),
        avatarUrl: z.string().optional(),
      }).optional(),
      authorTimestamp: z.number().optional(),
      committer: z.looseObject({
        name: z.string().optional(),
        emailAddress: z.string().optional(),
        active: z.boolean().optional(),
        displayName: z.string().optional(),
        id: z.number().optional(),
        slug: z.string().optional(),
        type: z.string().optional(),
        links: z.looseObject({
          self: z.array(z.looseObject({
            href: z.string().optional(),
          })).optional(),
        }).optional(),
        avatarUrl: z.string().optional(),
      }).optional(),
      committerTimestamp: z.number().optional(),
      message: z.string().optional(),
      parents: z.array(z.looseObject({
        id: z.string().optional(),
        displayId: z.string().optional(),
      })).optional(),
      properties: z.looseObject({
        commentCount: z.number().optional(),
      }).optional(),
    }).optional(),
    'com.atlassian.bitbucket.server.bitbucket-build:build-status-metadata': z.looseObject({
      cancelled: z.number().optional(),
      successful: z.number().optional(),
      inProgress: z.number().optional(),
      failed: z.number().optional(),
      unknown: z.number().optional(),
    }).optional(),
    'com.atlassian.bitbucket.server.bitbucket-ref-metadata:outgoing-pull-request-metadata': z.looseObject({
      pullRequest: z.looseObject({
        id: z.number().optional(),
        version: z.number().optional(),
        title: z.string().optional(),
        state: z.string().optional(),
        open: z.boolean().optional(),
        closed: z.boolean().optional(),
        draft: z.boolean().optional(),
        createdDate: z.number().optional(),
        updatedDate: z.number().optional(),
        fromRef: z.looseObject({
          id: z.string().optional(),
          displayId: z.string().optional(),
          latestCommit: z.string().optional(),
          type: z.string().optional(),
          repository: z.looseObject({
            slug: z.string().optional(),
            id: z.number().optional(),
            name: z.string().optional(),
            hierarchyId: z.string().optional(),
            scmId: z.string().optional(),
            state: z.string().optional(),
            statusMessage: z.string().optional(),
            forkable: z.boolean().optional(),
            project: z.looseObject({
              key: z.string().optional(),
              id: z.number().optional(),
              name: z.string().optional(),
              public: z.boolean().optional(),
              type: z.string().optional(),
            }).optional(),
            public: z.boolean().optional(),
            archived: z.boolean().optional(),
          }).optional(),
        }).optional(),
        toRef: z.looseObject({
          id: z.string().optional(),
          displayId: z.string().optional(),
          latestCommit: z.string().optional(),
          type: z.string().optional(),
          repository: z.looseObject({
            slug: z.string().optional(),
            id: z.number().optional(),
            name: z.string().optional(),
            hierarchyId: z.string().optional(),
            scmId: z.string().optional(),
            state: z.string().optional(),
            statusMessage: z.string().optional(),
            forkable: z.boolean().optional(),
            project: z.looseObject({
              key: z.string().optional(),
              id: z.number().optional(),
              name: z.string().optional(),
              public: z.boolean().optional(),
              type: z.string().optional(),
            }).optional(),
            public: z.boolean().optional(),
            archived: z.boolean().optional(),
          }).optional(),
        }).optional(),
        locked: z.boolean().optional(),
        author: z.looseObject({
          user: z.looseObject({
            name: z.string().optional(),
            emailAddress: z.string().optional(),
            active: z.boolean().optional(),
            displayName: z.string().optional(),
            id: z.number().optional(),
            slug: z.string().optional(),
            type: z.string().optional(),
          }).optional(),
          role: z.string().optional(),
          approved: z.boolean().optional(),
          status: z.string().optional(),
        }).optional(),
        reviewers: z.array(z.unknown()).optional(),
        participants: z.array(z.unknown()).optional(),
        closedDate: z.number().optional(),
      }).optional(),
    }).optional(),
  }).optional(),
});

export type RestBranch = z.infer<typeof RestBranchSchema>;
